name: Fist-workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: getting my code first
        uses: actions/checkout@v6
      - name: installing dependencies
        uses: actions/setup-node@v6
        with:
          node-version: '22.21.0'
      - name: installing dependencies
        run: npm install
      - name: testing my app
        run: npm test    